### ISSUE TITLE
Hugo modules mounted to content looks weird

### ISSUE THREAD

**Issue by codeasashu** [google/docsy-example#120]
I am using external hugo module to pull in remote content. My `config.toml` looks like this:

```toml
# ... rest of configs

[module]
  [[module.imports]]
    path = "github.com/craftsmandigital/markdown-content-repo"
    disabled = false

    [[module.imports.mounts]]
    source = "testing-hugo-modules"
    target = "content/test"
```

then visiting http://localhost:1313/test/file-1 does print the contents but its hidden behind the top menu. Screenshot below:

![image](https://user-images.githubusercontent.com/1492350/120101071-e2715a00-c161-11eb-934e-a453721e135d.png)

I am looking to pull in remote content using module ecosystem, using the docsy layout. Is it possible?

**Comment by codeasashu** [comment]
I've resolve this by changing the `target` in the mounts. So, this config works:

```toml
# ... rest of configs

[module]
  [[module.imports]]
    path = "github.com/craftsmandigital/markdown-content-repo"
    disabled = false

    [[module.imports.mounts]]
    source = "testing-hugo-modules"
    target = "content/docs/test"
```

Then visiting http://localhost:1313/docs/test/file-1 is working fine
