### ISSUE TITLE
Docker image for continuous integration

### ISSUE THREAD

**Issue by Nubonetics** [google/docsy-example#15]
I was wondering what Docker image can be used to publish docsy-example. The Hugo docker images that I have found don't support SCSS.

**Comment by klakegg** [comment]
My Docker image [klakegg/hugo](https://hub.docker.com/r/klakegg/hugo) should be suitable for Docsy users.

**Comment by JinnaBalu** [comment]
```yml
version: '3.6'
services:
  vibhivi:
    image: klakegg/hugo:0.64.0
    command: server
    volumes:
      - .:/src
    ports:
      - 1313:1313
```
