### ISSUE TITLE
Error: from config: failed to resolve output format "print" from site config

### ISSUE THREAD

**Issue by bhawanasachdeva** [google/docsy-example#166]
I have added docsy theme to my hugo site while running the below command 
 hugo serve -D 
 
I am getting below error :
Error: from config: failed to resolve output format "print" from site config

**Comment by wtchangdm** [comment]
Just remove the `"print"` in the following section of `config.toml`:

```toml
# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]
```
